#!/usr/bin/env bash
#
#  Demo 8: Snort pod 
#
set -euo pipefail

msg()
{
	local message="$1"
	local bold=$(tput bold)
	local normal=$(tput sgr0)

	echo "${bold}${message}${normal}"
}

waitUntilAllPodsRun()
{
	echo -en "\tWaiting for all pods to be deployed. This might take several minutes."

	while [[ "$(kubectl get -A pods --field-selector status.phase!=Running -o name)" != "" ]];
	do
		echo -n "."
		sleep 10
	done

	echo ""
}

readonly MINIKUBE_STATUS=$(minikube status | grep host | awk '{print $2}')

if [[ "$MINIKUBE_STATUS" == "Running" ]];
then
	echo "Please first stop/clean minikube before running the demo"
	exit 0
fi

minikube start \
    --vm-driver=docker \
    --network-plugin=cni \
    --cni=images/antrea.yml

msg "Adding Multus CNI"
kubectl apply \
    -f https://raw.githubusercontent.com/intel/multus-cni/master/images/multus-daemonset.yml \
    > /dev/null

waitUntilAllPodsRun

msg "Adding 2port network configuration"
kubectl apply -f yamls/2_port.yaml > /dev/null

readonly ANTREA_AGENT=$(kubectl get -A po | grep "antrea-agent" | awk '{print $2}')
readonly ANTREA_POD="kubectl -n kube-system exec -it $ANTREA_AGENT -c antrea-agent -- "
readonly ANTREA_EXEC="kubectl -n kube-system exec $ANTREA_AGENT -c antrea-agent -- "

msg "Adding pods"
kubectl apply -f yamls/pods > /dev/null

waitUntilAllPodsRun

# Setup pods names and ip addresses
readonly ALICE_POD_1=alice1
readonly ALICE_POD_2=alice2
readonly ALICE_POD_3=alice3
readonly MALICE_POD=malice1
readonly SYSLOG_POD=syslog
readonly SNORT_POD=snort
readonly SNORT_PORT=$($ANTREA_POD ovs-vsctl show | grep -oE "snort-.{6}" | head -1)
readonly SYSLOG_IP=$(kubectl exec -it syslog -- ip a | grep inet | awk '{print $2}' | sed '3!d' |  awk -F/ '{print $1}')
readonly ANTREA_IP=$(kubectl get -A po -o wide | grep antrea-agent | awk '{print $7}')

msg "Starting mirroring on snort port"
$ANTREA_POD ovs-vsctl \
  -- --id=@p get port $SNORT_PORT \
  -- --id=@m create mirror name=m0 select-all=true output-port=@p \
  -- set bridge br-int mirrors=@m &> /dev/null

echo -e "\n\n"

msg "End of demo8!"

echo -e "\tUse 'minikube stop' to bring kubernetes cluster down"
echo -e "\tUse 'minikube delete' to clean kubernetes cluster"