#!/usr/bin/env bash
#
#  Demo 6: Flow recording 
#
set -euo pipefail

source ../common/scripts/funcs.sh

readonly MINIKUBE_STATUS=$(minikube status | grep host | awk '{print $2}')

if [[ "$MINIKUBE_STATUS" == "" ]];
then
	echo "Please run '../deploy.sh' first to start the cluster"
	exit 0
fi

msg "Adding tsi security"
kubectl apply -f yamls/security

msg "Adding demo pods"
kubectl apply -f yamls/pods

waitUntilAllPodsRun

readonly AGENT_POD=$(kubectl get -A po -o wide | grep "agent-server" | awk '{print $2}')
readonly AGENT_IP=$(kubectl get -A po -o wide | grep "agent-server" | awk '{print $7}')
readonly FLOW_CONTROL_POD=$(kubectl get -A po | grep "flow-control" | awk '{print $2}')

# Setup pods names and ip addresses
readonly ALICE_POD_1=alice1
readonly ALICE_POD_2=alice2
readonly ALICE_POD_3=alice3

msg "Sending a request to google.com"
kubectl exec $ALICE_POD_1 -- ping -c3 google.com

msg "Sending a request to amazon.com"
kubectl exec $ALICE_POD_2 -- ping -c3 amazon.com

msg "Aplied ovs rules"
kubectl exec -n security "$AGENT_POD" -- bash -c "ovs-ofctl dump-flows br-int | grep 0x0"

msg "Cleaning cluster"
kubectl exec -n security "$AGENT_POD" -- bash -c "ovs-ofctl del-flows br-int cookie=0x0/-1" &> /dev/null || true
sleep 1

kubectl delete -f yamls/security
kubectl delete -f yamls/pods
