#!/usr/bin/env bash
#
#  Demo 6: Flow recording 
#
set -euo pipefail

source ../common/scripts/funcs.sh

readonly MINIKUBE_STATUS=$(minikube status | grep host | awk '{print $2}')

if [[ "$MINIKUBE_STATUS" == "" ]];
then
	echo "Please run '../deploy.sh' first to start the cluster"
	exit 0
fi

msg "Adding 2port network configuration"
kubectl apply -f yamls/2_port.yaml > /dev/null

readonly ANTREA_AGENT=$(kubectl get -A po | grep "antrea-agent" | awk '{print $2}')
readonly ANTREA_POD="kubectl -n kube-system exec -it $ANTREA_AGENT -c antrea-agent -- "
readonly ANTREA_EXEC="kubectl -n kube-system exec $ANTREA_AGENT -c antrea-agent -- "

msg "Adding pods"
kubectl apply -f yamls/pods > /dev/null

waitUntilAllPodsRun

msg "Adding services"
kubectl apply -f yamls/services > /dev/null

# Setup pods names and ip addresses
readonly ALICE_POD_1=alice1
readonly ALICE_POD_2=alice2
readonly ALICE_POD_3=alice3
readonly MALICE_POD=malice
readonly LOGGER_POD=logger
readonly ANALYSER_POD=analyser
readonly ANALYSER_PORT=$($ANTREA_POD ovs-vsctl show | grep -oE "analyser-.{6}" | head -1)
readonly LOGGER_IP=$(kubectl exec -it logger -- ip a | grep inet | awk '{print $2}' | sed '3!d' |  awk -F/ '{print $1}')
readonly ANTREA_IP=$(kubectl get -A po -o wide | grep antrea-agent | awk '{print $7}')
readonly SERVICES_IP=$(minikube ip)


msg "Starting logger server"
kubectl exec "$LOGGER_POD" -- bash -c "nohup python3 logger_server.py &"
sleep 5



msg "Sending a request to google.com"
kubectl exec $ALICE_POD_1 -- ping -c3 google.com
sleep 2

msg "Sending a request to amazon.com"
kubectl exec $ALICE_POD_2 -- ping -c3 amazon.com
sleep 2

msg "Fetch data from cluster using local program"
python3 utils/logger_client.py -i "{\"send_ip\":\"$SERVICES_IP\", \"send_port\":\"30062\"}"



msg "Aplied ovs rules"
kubectl exec -n security "$AGENT_POD" -- bash -c "ovs-ofctl dump-flows br-int | grep 0x0"

msg "Cleaning cluster"
kubectl exec -n security "$AGENT_POD" -- bash -c "ovs-ofctl del-flows br-int cookie=0x0/-1" &> /dev/null || true
sleep 1
kubectl delete -f yamls/security
kubectl delete -f yamls/pods
