#!/usr/bin/env bash
#
#  Demo 3 - Throttle traffic 
#
set -euo pipefail

source ../common/scripts/funcs.sh

readonly MINIKUBE_STATUS=$(minikube status | grep host | awk '{print $2}')

if [[ "$MINIKUBE_STATUS" == "" ]];
then
	echo "Please run '../deploy.sh' first to start the cluster"
	exit 0
fi

msg "Adding tsi yaml"
kubectl apply -f yamls/security

waitUntilAllPodsRun

msg "Adding demo pods"
kubectl apply -f yamls/pods

waitUntilAllPodsRun

readonly AGENT_SERVER=$(kubectl get -A po | grep "agent-server" | awk '{print $2}')
readonly AGENT_IP=$(kubectl get -A po -o wide | grep -w "$AGENT_SERVER" | awk '{print $7}')
readonly AGENT_EXEC="kubectl -n security exec $AGENT_SERVER -- "

readonly NETPERF_SERVER_POD=host
readonly NETPERF_CLIENT1_POD=client1
readonly NETPERF_CLIENT2_POD=client2
readonly FLOW_CONTROL_POD=flow-control
readonly NETPERF_SERVER_IP=$(kubectl get -A po -o wide | grep -w "$NETPERF_SERVER_POD" | awk '{print $7}')
readonly NETPERF_CLIENT1_PORT=$($AGENT_EXEC ovs-vsctl show | grep $NETPERF_CLIENT1_POD | awk '{print $2}' | head -1)
readonly NETPERF_CLIENT2_PORT=$($AGENT_EXEC ovs-vsctl show | grep $NETPERF_CLIENT2_POD | awk '{print $2}' | head -1)

msg "Starting Demo"

msg "Starting netperf server on the measurement"
kubectl exec "$NETPERF_SERVER_POD" -- netserver

msg "Verify throughput value for $NETPERF_CLIENT1_POD"
kubectl exec -it "$NETPERF_CLIENT1_POD" -- netperf -H $NETPERF_SERVER_IP 

msg "Verify throughput value for $NETPERF_CLIENT2_POD"
kubectl exec -it "$NETPERF_CLIENT2_POD" -- netperf -H $NETPERF_SERVER_IP 

msg "Limiting rate of $NETPERF_CLIENT1_POD to 1 Mbps"
kubectl exec "$FLOW_CONTROL_POD" -- bash -c "python3 home/forward.py -l=$AGENT_IP -lp=8080 -s=$AGENT_IP -sp=12345 -i='{\"action\": \"throttle\", \"argument\": {\"port\": \"$NETPERF_CLIENT1_PORT\", \"limit\": \"1\"}}'"

msg "Limiting rate of $NETPERF_CLIENT2_POD to 10 Mbps"
kubectl exec "$FLOW_CONTROL_POD" -- bash -c "python3 home/forward.py -l=$AGENT_IP -lp=8080 -s=$AGENT_IP -sp=12345 -i='{\"action\": \"throttle\", \"argument\": {\"port\": \"$NETPERF_CLIENT2_PORT\", \"limit\": \"10\"}}'"

msg "Verify throughput value for $NETPERF_CLIENT1_POD"
kubectl exec -it "$NETPERF_CLIENT1_POD" -- netperf -H $NETPERF_SERVER_IP 

msg "Verify throughput value for $NETPERF_CLIENT2_POD"
kubectl exec -it "$NETPERF_CLIENT2_POD" -- netperf -H $NETPERF_SERVER_IP 

msg "Cleaning cluster"

kubectl delete -f yamls/security/
kubectl delete -f yamls/pods

msg "End of demo3!"