apiVersion: v1
kind: Pod
metadata:
  name: analyser 
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  containers:
  - name: analyser
    image: 192.168.49.1:5000/tsi-analyser:v1.6.0
    command:
      - sleep
      - infinity
    imagePullPolicy: Always 

