apiVersion: v1
kind: Pod
metadata:
  labels:
    app: logger 
  name: logger 
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  containers:
  - name: logger 
    image: 192.168.49.1:5000/tsi-logger:v1.6.0
    command:
      - sleep
      - infinity
    imagePullPolicy: Always
    ports:
      - containerPort: 8006
