apiVersion: v1
kind: Pod
metadata:
  name: host
spec:
  containers:
    - name: host
      image: paultiplady/netperf
      command:
        - sleep
        - infinity
      imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Pod
metadata:
  name: client1
spec:
  containers:
    - name: client1
      image: paultiplady/netperf
      command:
        - sleep
        - infinity
      imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Pod
metadata:
  name: client2
spec:
  containers:
    - name: client2
      image: paultiplady/netperf
      command:
        - sleep
        - infinity
      imagePullPolicy: IfNotPresent
