#!/usr/bin/env bash
set -euo pipefail

msg()
{
	local message="$1"
	local bold=$(tput bold)
	local normal=$(tput sgr0)

	echo "${bold}${message}${normal}"
}

waitUntilAllPodsRun()
{
	echo -en "\tWaiting for all pods to be deployed. This might take several minutes."

	while [[ "$(kubectl get -A pods --field-selector status.phase!=Running -o name)" != "" ]];
	do
		echo -n "."
		sleep 10
	done

	echo ""
}


# Setup Antrea Agent alias
readonly ANTREA_AGENT=$(kubectl get -A po | grep "antrea-agent" | awk '{print $2}')
readonly ANTREA_POD="kubectl -n kube-system exec -it $ANTREA_AGENT -c antrea-agent -- "
sleep 5


readonly DGA=$($ANTREA_POD ovs-vsctl show | grep dga | awk '{print $2}' | sed '2!d')
# Setup pods names and ip addresses
readonly ALICE_POD_1=alice1
readonly ALICE_POD_2=alice2
readonly ALICE_POD_3=alice3
readonly MALICE_POD=malice
readonly FLOW_CONTROL_POD=flow-control

readonly FLOW_CONTROL_IP=$(kubectl exec -it flow-control -- ip a | grep inet | awk '{print $2}' | sed '3!d' |  awk -F/ '{print $1}')
readonly ANTREA_IP=192.168.42.2

echo "lalal$DGA"
msg "Starting mirroring on dga port"
$ANTREA_POD ovs-vsctl \
  -- --id=@p get port $DGA \
  -- --id=@m create mirror name=m0 select-all=true output-port=@p \
  -- set bridge br-int mirrors=@m

sleep 5

msg "Starting dga service"
kubectl exec -it dga -- bash -c "python3 monitor.py -m dga.model -a $FLOW_CONTROL_IP &" 
sleep 5

msg "Starting Demo"

msg "Send a non-malicius nslookup request from $ALICE_POD_1" 
kubectl exec -it "$ALICE_POD_1" -- nslookup google.com
sleep 5

msg "Send a non-malicius nslookup request from $ALICE_POD_2" 
kubectl exec -it "$ALICE_POD_2" -- nslookup amazon.com 
sleep 5

msg "Send a non-malicius nslookup request from $ALICE_POD_3" 
kubectl exec -it "$ALICE_POD_3" -- nslookup netflix.com 
sleep 5

msg "Send a malicius nslookup request from $MALICE_POD" 
kubectl exec -it "$MALICE_POD" -- nslookup gqoppwnan.com 
sleep 5

msg "Connectivity from $MALICE_POD should be terminated automaticaly"

msg "Verify that there is no connectivity from $MALICE_POD" 
kubectl exec -it "$MALICE_POD" -- ping -c3 gqoppwnan.com && true
sleep 5

echo -e "\n\n"

msg "End of demo2!"
echo -e "\tUse 'minikube stop' to bring kubernetes cluster down"
echo -e "\tUse 'minikube delete' to clean kubernetes cluster"
