#!/usr/bin/env bash
#
#  Demo 9: DDoS Attack
#
set -euo pipefail

source ../common/scripts/funcs.sh

msg "Adding demo pods"
kubectl apply -f yamls/pods

msg "Adding tsi security"
kubectl apply -f yamls/security

waitUntilAllPodsRun

readonly AGENT_POD_1=$(kubectl get -A po -o wide | grep "agent-server" | head -1 | awk '{print $2}')
readonly AGENT_POD_2=$(kubectl get -A po -o wide | grep "agent-server" | tail -1 | awk '{print $2}')
readonly API=$(kubectl get po -o wide -n security | grep "api" | awk '{print $1}')
readonly ALICE_POD_1=alice
readonly MALICE_POD_1=malice1
readonly MALICE_POD_2=malice2
readonly MALICE_POD_3=malice3
readonly MALICE_POD_4=malice4
readonly MALICE_POD_5=malice5
readonly MALICE_POD_6=malice6

msg "Adding queues on demo pods"
kubectl exec -n security "$AGENT_POD_1" -- bash -c "ovs-vsctl list-ports br-int | xargs -d '\n' -I{} ovs-vsctl set port {} qos=@newqos -- \
  --id=@newqos create qos type=linux-htb \
      queues:100=@queue -- \
  --id=@queue create queue other-config:max-rate=1000000 &> /dev/null"

kubectl exec -n security "$AGENT_POD_2" -- bash -c "ovs-vsctl list-ports br-int | xargs -d '\n' -I{} ovs-vsctl set port {} qos=@newqos -- \
  --id=@newqos create qos type=linux-htb \
      queues:100=@queue -- \
  --id=@queue create queue other-config:max-rate=1000000 &> /dev/null"

msg "Starting Demo"

msg "Sending normal requests to web-site from alice" 
kubectl exec "$ALICE_POD_1" -- bash -c "nohup ./httpClient -conn=http://147.27.39.116:8080/ &"

msg "Deploying canary client to monitor the health of the website" 
kubectl exec -it "$API" -n security -- ./client -c "create canary"

readonly CANARY=$(kubectl get po -o wide -n security | grep "canary" | awk '{print $1}')

msg "Please open a new terminal and execute the following command" 
echo "kubectl exec -it $CANARY -n security -- tail -f canary.log"
read -p "Press enter to continue"

msg "Creating DDoS traffic from malicious pods"
kubectl exec "$MALICE_POD_1" -- bash -c "nohup ./httpClient -conn=http://147.27.39.116:8080/ -c 100 -s 0 &"
kubectl exec "$MALICE_POD_2" -- bash -c "nohup ./httpClient -conn=http://147.27.39.116:8080/ -c 100 -s 0 &"
kubectl exec "$MALICE_POD_3" -- bash -c "nohup ./httpClient -conn=http://147.27.39.116:8080/ -c 100 -s 0 &"
kubectl exec "$MALICE_POD_4" -- bash -c "nohup ./httpClient -conn=http://147.27.39.116:8080/ -c 100 -s 0 &"
kubectl exec "$MALICE_POD_5" -- bash -c "nohup ./httpClient -conn=http://147.27.39.116:8080/ -c 100 -s 0 &"
kubectl exec "$MALICE_POD_6" -- bash -c "nohup ./httpClient -conn=http://147.27.39.116:8080/ -c 100 -s 0 &"

msg "All the malicious pods should be limited and the canary log restored to normal" 

echo -e "\n\n"

msg "Cleaning cluster"
sleep 1
# kubectl delete -f yamls/security
# kubectl delete -f yamls/pods

msg "End of demo9!"
