---

- hosts: kube_cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: docker, tags: docker }

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/master, tags: master }
    - { role: cni, tags: cni }

- hosts: worker
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/worker, tags: worker }
