#!/usr/bin/env bash
set -euo pipefail

msg()
{
	local message="$1"
	local bold=$(tput bold)
	local normal=$(tput sgr0)

	echo "${bold}${message}${normal}"
}

waitUntilAllPodsRun()
{
	echo -en "\tWaiting for all pods to be deployed. This might take several minutes."

	while [[ "$(kubectl get -A pods --field-selector status.phase!=Running -o name)" != "" ]];
	do
		echo -n "."
		sleep 10
	done

	echo ""
}

readonly MINIKUBE_STATUS=$(minikube status | grep host | awk '{print $2}')
readonly REGISTRY_STATUS=$(docker ps | grep registry:2 | awk '{print $2}')

if [[ "$MINIKUBE_STATUS" == "Running" ]];
then
	echo "Please first stop/clean minikube before running the demo"
	exit 0
fi

if [[ "$REGISTRY_STATUS" == "registry:2" ]];
then
	echo "Please first clean local registry before running the demo"
	exit 0
fi

msg "Starting local docker registry"

docker run -d -p 5000:5000 --restart=always --name registry registry:2

msg "Creating flow-control docker image"

docker build flow-control -t flow-control:v1.0.0
docker tag flow-control:v1.0.0 localhost:5000/flow-control:v1.0.0
docker push localhost:5000/flow-control:v1.0.0
sleep 5

msg "Starting minikube cluster"

minikube start \
    --vm-driver=docker \
    --network-plugin=cni \
    --extra-config=kubeadm.pod-network-cidr=172.16.0.0/16 \
    --extra-config=kubelet.network-plugin=cni \
    --insecure-registry="192.168.49.1:5000"

msg "Adding Antrea CNI"

kubectl apply \
    -f https://github.com/vmware-tanzu/antrea/releases/download/v0.12.0/antrea.yml \
    > /dev/null

waitUntilAllPodsRun

# Setup Antrea Agent alias
readonly ANTREA_AGENT=$(kubectl get -A po | grep "antrea-agent" | awk '{print $2}')
readonly ANTREA_POD="kubectl -n kube-system exec -it $ANTREA_AGENT -c antrea-agent -- "
sleep 5

msg "Adding demo pods"
kubectl apply -f yamls > /dev/null

waitUntilAllPodsRun

msg "Setting up dga network monitoring"

msg "Copying tcp server code to antrea agent"
kubectl cp agent_server.py kube-system/$ANTREA_AGENT:home/

# Setup pods names and ip addresses
readonly ALICE_POD_1=alice
readonly MALICE_POD=malice
readonly ALICE_IP=$(kubectl get -A po -o wide | grep -w "$ALICE_POD_1" | awk '{print $7}')
readonly MALICE_IP=$(kubectl get -A po -o wide | grep -w "$MALICE_POD" | awk '{print $7}')
readonly FLOW_CONTROL_POD=flow-control
readonly ANTREA_IP=192.168.49.2

msg "Starting antrea-agent server"
kubectl -n kube-system exec $ANTREA_AGENT -c antrea-agent -- bash -c "nohup python3 home/agent_server.py > /dev/null 2> /dev/null &"
sleep 10

msg "Starting Demo"

msg "Verify connectivity between $ALICE_POD_1 and $MALICE_POD" 
kubectl exec -it "$MALICE_POD" -- ping -c3 "$ALICE_IP"
sleep 5

msg "Block malice ip through flow-control service"
kubectl exec "$FLOW_CONTROL_POD" -- bash -c "python3 forward.py -b $MALICE_IP -s $ANTREA_IP"
sleep 10

msg "Verify that there is no connectivity between $ALICE_POD_1 and $MALICE_POD" 
kubectl exec -it "$MALICE_POD" -- ping -c3 -W1 "$ALICE_IP" && true
sleep 5

#msg "Removing OpenFlow rule to block traffic from $MALICE_POD"
#$ANTREA_POD ovs-ofctl del-flows --strict br-int in_port="$MALICE_PORT",nw_src=$MALICE_IP

#msg "Verify connectivity between $ALICE_POD and $MALICE_POD is back" 
#kubectl exec -it "$MALICE_POD" -- ping -c3 "$ALICE_IP"

echo -e "\n\n"

msg "End of demo1!"
echo -e "\tUse 'minikube stop' to bring kubernetes cluster down"
echo -e "\tUse 'minikube delete' to clean kubernetes cluster"
