apiVersion: v1
kind: Namespace
metadata:
  name: security
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: security
  name: agent-server
  namespace: security
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: security
    component: agent-server
  name: agent-server
  namespace: security
spec:
  selector:
    matchLabels:
      app: security
      component: agent-server
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: agent-server
      labels:
        app: security
        component: agent-server
    spec:
      containers:
        - env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command:
            - /usr/bin/python3
          args:
            - /home/agent_server.py
            - -i=$(MY_POD_IP)
            - -p=12345
            - -l=True
          image: 192.168.49.1:5000/antrea-tsi:v1.0.0
          imagePullPolicy: IfNotPresent
          name: agent-server
          ports:
            - containerPort: 12345
              hostPort: 12345
              protocol: TCP
          resources:
            requests:
              cpu: 200m
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/run/openvswitch
              name: host-var-run-antrea
              subPath: openvswitch
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      serviceAccountName: agent-server
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
        - hostPath:
            path: /var/run/antrea
            type: DirectoryOrCreate
          name: host-var-run-antrea
  updateStrategy:
    type: RollingUpdate
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: security
    component: flow-control
  name: flow-control
  namespace: security
spec:
  selector:
    matchLabels:
      app: security
      component: flow-control
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: flow-control
      labels:
        app: security
        component: flow-control
    spec:
      containers:
        - command:
            - sleep
            - infinity
          image: 192.168.49.1:5000/tsi-flow-control:common
          imagePullPolicy: IfNotPresent
          name: flow-control
          resources:
            requests:
              cpu: 200m
      nodeSelector:
        kubernetes.io/os: linux
  updateStrategy:
    type: RollingUpdate
