apiVersion: v1
kind: Pod
metadata:
  name: malice
spec:
  containers:
    - name: malice
      image: mkrishnamurthy/nslookup
      command:
        - sleep
        - infinity
      imagePullPolicy: IfNotPresent
