apiVersion: apps/v1
kind: DaemonSet
metadata:
   name: iperf3
   labels:
      app: iperf3
spec:
   selector:
      matchLabels:
        app: iperf3
   template:
      metadata:
         labels:
            app: iperf3
      spec:
         containers:
         -  name: iperf3
            image: 130.207.224.36:5000/antrea-tsi:v1.0.0
            command: ['/bin/sh', '-c', 'sleep 1d']
            ports:
            - containerPort: 5201
