# Ansible user
ansible_user: gntousakis 

# Networks for kubernetes deployment
pod_network_cidr: "10.244.0.0/16"

# Extra variables
systemd_dir: /lib/systemd/system
system_env_dir: /etc/sysconfig
network_dir: /etc/kubernetes/network
kubeadmin_config: /etc/kubernetes/admin.conf
kube_addon_dir: /etc/kubernetes/addon
