apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-dnn11
  labels:
    app: oai-dnn11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-dnn11
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oai-dnn11
      annotations:
        k8s.v1.cni.cncf.io/networks: dnn-net1
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: dnn
        image: tolgaomeratalay/oai-dnn:latest
        #command: ['bash', '-c', "iptables -t nat -A POSTROUTING -o net1 -j MASQUERADE; ip route add 12.1.0.0/16 via 192.168.15.10 dev net1;"]
        #command: ["/bin/bash"]
        #args: ["-c", "iptables -t nat -A POSTROUTING -o net1 -j MASQUERADE;ip route add 12.1.0.0/16 via 192.168.15.10 dev net1;"]
        #  - iptables -t nat -A POSTROUTING -o net1 -j MASQUERADE;
        #  - ip route add 12.1.0.0/16 via 192.168.15.10 dev net1;
        command:
          - sleep
          - infinity
        imagePullPolicy: Always
        securityContext:
          privileged: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
