apiVersion: v1
kind: Namespace
metadata:
  name: security
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: security
  name: agent-server
  namespace: security
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: security
    component: agent-server
  name: agent-server
  namespace: security
spec:
  selector:
    matchLabels:
      app: security
      component: agent-server
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: agent-server
      labels:
        app: security
        component: agent-server
    spec:
      containers:
        - env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command:
            - /usr/bin/python3
          args:
            - /home/agent_server.py
            - -i=$(MY_POD_IP)
            - -p=12345
            - -l=True
          image: 192.168.49.1:5000/antrea-tsi:v1.0.0
          imagePullPolicy: IfNotPresent
          name: agent-server
          ports:
            - containerPort: 12345
              hostPort: 12345
              protocol: TCP
          resources:
            requests:
              cpu: 200m
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/run/antrea
              name: host-var-run-antrea
            - mountPath: /var/run/openvswitch
              name: host-var-run-antrea
              subPath: openvswitch
            - mountPath: /var/lib/cni
              name: host-var-run-antrea
              subPath: cni
            - mountPath: /var/log/antrea
              name: host-var-log-antrea
            - mountPath: /host/proc
              name: host-proc
              readOnly: true
            - mountPath: /host/var/run/netns
              mountPropagation: HostToContainer
              name: host-var-run-netns
              readOnly: true
            - mountPath: /run/xtables.lock
              name: xtables-lock
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      serviceAccountName: agent-server
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
        - configMap:
            name: antrea-config-5ct9ktdt77
          name: antrea-config
        - hostPath:
            path: /etc/cni/net.d
          name: host-cni-conf
        - hostPath:
            path: /opt/cni/bin
          name: host-cni-bin
        - hostPath:
            path: /proc
          name: host-proc
        - hostPath:
            path: /var/run/netns
          name: host-var-run-netns
        - hostPath:
            path: /var/run/antrea
            type: DirectoryOrCreate
          name: host-var-run-antrea
        - hostPath:
            path: /var/log/antrea
            type: DirectoryOrCreate
          name: host-var-log-antrea
        - hostPath:
            path: /lib/modules
          name: host-lib-modules
        - hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
          name: xtables-lock
  updateStrategy:
    type: RollingUpdate
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
  namespace: security
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "capabilities": { "ips": true },
    "master": "eth0",
    "mode": "bridge",
    "ipam": {
    "type": "static",
    "routes": [
    {
    "dst": "0.0.0.0/0",
    "gw": "10.1.1.1"
    }
    ]
    }
    }'
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: security
    component: flow-control
  name: flow-control
  namespace: security
spec:
  selector:
    matchLabels:
      app: security
      component: flow-control
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: flow-control
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "macvlan-conf",
          "ips": [ "10.1.1.101/24" ],
          "mac": "c2:b0:57:49:47:f1",
          "gateway": [ "10.1.1.1" ]
          }]'
      labels:
        app: security
        component: flow-control
    spec:
      containers:
        - env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          command:
            - /usr/bin/python3
          args:
            - /home/forward.py
            - -l=10.1.1.101
            - -lp=8080
            - -s=$(MY_HOST_IP)
            - -sp=12345
          image: 192.168.49.1:5000/tsi-flow-control:common
          imagePullPolicy: IfNotPresent
          name: flow-control
          resources:
            requests:
              cpu: 200m
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
  updateStrategy:
    type: RollingUpdate
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: security
    component: dga
  name: dga
  namespace: security
spec:
  selector:
    matchLabels:
      app: security
      component: dga
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: dga
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "macvlan-conf",
          "ips": [ "10.1.1.102/24" ],
          "mac": "c2:b0:57:49:47:f2",
          "gateway": [ "10.1.1.1" ]
          }]'
      labels:
        app: security
        component: dga
    spec:
      containers:
        - command:
            - /usr/bin/python3
          args:
            - /tmp/monitor.py
            - -m=/tmp/dga.model
            - -a=10.1.1.101
            - -p=8080
          image: 192.168.49.1:5000/tsi-dga:common
          imagePullPolicy: IfNotPresent
          name: dga
          resources:
            requests:
              cpu: 200m
      initContainers:
        - name: init-mirror
          image: 192.168.49.1:5000/antrea-tsi:v1.0.0
          command: ["sh", "-c", "/home/mirror-port.sh"]
          volumeMounts:
            - mountPath: /var/run/openvswitch
              name: host-var-run-antrea
              subPath: openvswitch
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
        - hostPath:
            path: /var/run/antrea
            type: DirectoryOrCreate
          name: host-var-run-antrea
  updateStrategy:
    type: RollingUpdate
