#!/usr/bin/env bash
#
#  Demo 9: DDoS Attack
#
set -euo pipefail

source ../common/scripts/funcs.sh

msg "Adding tsi security"
kubectl apply -f yamls/security

msg "Adding demo pods"
kubectl apply -f yamls/pods

waitUntilAllPodsRun

readonly AGENT_POD_1=$(kubectl get -A po -o wide | grep "flow-server" | head -1 | awk '{print $2}')
readonly AGENT_POD_2=$(kubectl get -A po -o wide | grep "flow-server" | tail -1 | awk '{print $2}')
readonly ANTREA_POD_1=$(kubectl get -A po -o wide | grep "antrea-agent" | head -1 | awk '{print $2}')
readonly ANTREA_POD_2=$(kubectl get -A po -o wide | grep "antrea-agent" | tail -1 | awk '{print $2}')
readonly API=$(kubectl get po -o wide -n security | grep "api" | awk '{print $1}')
readonly ALICE_POD_1=alice
readonly MALICE_POD_1=malice1
readonly MALICE_POD_2=malice2
readonly MALICE_POD_3=malice3
readonly MALICE_POD_4=malice4
readonly MALICE_POD_5=malice5
readonly MALICE_POD_6=malice6
readonly MALICE_POD_7=malice7
readonly MALICE_POD_8=malice8
readonly MALICE_POD_9=malice9
readonly MALICE_POD_10=malice10
readonly MALICE_POD_11=malice11
readonly MALICE_POD_12=malice12

sleep 4 

msg "Adding queues on demo pods"
kubectl exec -n security "$AGENT_POD_1" -- bash -c "ovs-vsctl list-ports br-int | egrep 'alice|malice' | xargs -d '\n' -I{} ovs-vsctl set port {} qos=@newqos -- \
  --id=@newqos create qos type=linux-htb \
      queues:100=@queue -- \
  --id=@queue create queue other-config:max-rate=100 &> /dev/null"

kubectl exec -n security "$AGENT_POD_2" -- bash -c "ovs-vsctl list-ports br-int | egrep 'alice|malice' | xargs -d '\n' -I{} ovs-vsctl set port {} qos=@newqos -- \
  --id=@newqos create qos type=linux-htb \
      queues:100=@queue -- \
  --id=@queue create queue other-config:max-rate=100 &> /dev/null"

PS3="Select demo: "
select option in "DDoS with application level canary" "DDoS with link level canary" Exit
do
  case $option in
    "DDoS with application level canary")
      msg "Starting DDoS Demo"
     	 
      read -p "Enter canary deployment command: " canaryCommands

      read -p "Enter detector deployment command: " detectorCommands
      
      msg "Deploying canary client to monitor the health of the website (4 failures to spawn detector)" 
      kubectl exec -it "$API" -n security -- ./client -arg "$canaryCommands"
      
      msg "Deploying detector with mirroring but with BPF filter disabled" 
      kubectl exec -it "$API" -n security -- ./client -arg "$detectorCommands"
      
      msg "Sending normal requests to http://kronos.mhl.tuc.gr:30001/ from alice" 
      kubectl exec "$ALICE_POD_1" -- bash -c "nohup /home/tsi/bin/client -conn=http://kronos.mhl.tuc.gr:30001/ &"

      waitUntilAllPodsRun
      
      CANARY_1=$(kubectl get po -o wide -n security | grep "canary" | awk '{print $1}' | head -1)
      CANARY_2=$(kubectl get po -o wide -n security | grep "canary" | awk '{print $1}' | tail -1)

      msg "Please open two new terminals and execute the following commands" 
      echo "kubectl exec -it $CANARY_1 -n security -- tail -f canary.log"
      echo "kubectl exec -it $CANARY_2 -n security -- tail -f canary.log"
      read -p "Press enter to continue"
      
      msg "Creating DDoS traffic from malicious pods"
      kubectl exec "$MALICE_POD_1" -- bash -c "nohup /home/tsi/bin/client -conn=http://kronos.mhl.tuc.gr:30001/ -c 100 -s 0 -t 0  &"
      kubectl exec "$MALICE_POD_2" -- bash -c "nohup /home/tsi/bin/client -conn=http://kronos.mhl.tuc.gr:30001/ -c 100 -s 0 -t 0  &"
      kubectl exec "$MALICE_POD_3" -- bash -c "nohup /home/tsi/bin/client -conn=http://kronos.mhl.tuc.gr:30001/ -c 100 -s 0 -t 0  &"
      kubectl exec "$MALICE_POD_4" -- bash -c "nohup /home/tsi/bin/client -conn=http://kronos.mhl.tuc.gr:30001/ -c 100 -s 0 -t 0  &"
      kubectl exec "$MALICE_POD_5" -- bash -c "nohup /home/tsi/bin/client -conn=http://kronos.mhl.tuc.gr:30001/ -c 100 -s 0 -t 0 &"
      kubectl exec "$MALICE_POD_6" -- bash -c "nohup /home/tsi/bin/client -conn=http://kronos.mhl.tuc.gr:30001/ -c 100 -s 0 -t 0 &"
      sleep 2

      msg "Waiting for the Web server to be responsive again" 
      read -p "Press enter to continue"
     
      msg "Removing canary deployment" 
      kubectl exec -it "$API" -n security -- ./client -arg "{\"action\":\"delete\", \"target\": \"canary\", \"arguments\": []}" 
      
      msg "Removing detector deployment" 
      kubectl exec -it "$API" -n security -- ./client -arg "{\"action\":\"delete\", \"target\": \"detector\", \"arguments\": []}"

      msg "Cleaning cluster"
      kubectl exec -n security "$AGENT_POD_1" -- bash -c "ovs-ofctl del-flows br-int cookie=0x0/-1" &> /dev/null || true
      kubectl exec -n security "$AGENT_POD_2" -- bash -c "ovs-ofctl del-flows br-int cookie=0x0/-1" &> /dev/null || true
      
      kubectl exec -n security "$AGENT_POD_1" -- bash -c "ovs-vsctl clear bridge br-int mirrors"
      kubectl exec -n security "$AGENT_POD_2" -- bash -c "ovs-vsctl clear bridge br-int mirrors"

      echo -e "\n"
      ;;
    "DDoS with link level canary")
      msg "Starting DDoS Link Demo"
      
      read -p "Enter canary deployment command: " canaryCommands

      read -p "Enter detector deployment command: " detectorCommands
      
      msg "Deploying link canary client to monitor the health of the website (4 failures to spawn detector)" 
      kubectl exec -it "$API" -n security -- ./client -arg "$canaryCommands"
      
      msg "Deploying detector with mirroring but with BPF filter disabled" 
      kubectl exec -it "$API" -n security -- ./client -arg "$detectorCommands"

      msg "Sending normal requests to http://kronos.mhl.tuc.gr:30002/ from alice" 
      kubectl exec "$ALICE_POD_1" -- bash -c "nohup /home/tsi/bin/client -conn=http://kronos.mhl.tuc.gr:30002/ -s 10 &"

      CANARY_1=$(kubectl get po -o wide -n security | grep "canary" | awk '{print $1}' | head -1)
      CANARY_2=$(kubectl get po -o wide -n security | grep "canary" | awk '{print $1}' | tail -1)

      msg "Please open two new terminals and execute the following commands" 
      echo "kubectl exec -it $CANARY_1 -n security -- tail -f canary-link.log"
      echo "kubectl exec -it $CANARY_2 -n security -- tail -f canary-link.log"
      read -p "Press enter to continue"

      msg "Creating DDoS traffic from malicious pods"
      kubectl exec "$MALICE_POD_7" -- bash -c "nohup /home/tsi/bin/client -conn=http://kronos.mhl.tuc.gr:30002/ -c 100 -s 0 -t 0 &"
      kubectl exec "$MALICE_POD_8" -- bash -c "nohup /home/tsi/bin/client -conn=http://kronos.mhl.tuc.gr:30002/ -c 100 -s 0 -t 0 &"
      kubectl exec "$MALICE_POD_9" -- bash -c "nohup /home/tsi/bin/client -conn=http://kronos.mhl.tuc.gr:30002/ -c 100 -s 0  -t 0 &"
      kubectl exec "$MALICE_POD_10" -- bash -c "nohup /home/tsi/bin/client -conn=http://kronos.mhl.tuc.gr:30002/ -c 100 -s 0 -t 0 &"
      kubectl exec "$MALICE_POD_11" -- bash -c "nohup /home/tsi/bin/client -conn=http://kronos.mhl.tuc.gr:30002/ -c 100 -s 0 -t 0 &"
      kubectl exec "$MALICE_POD_12" -- bash -c "nohup /home/tsi/bin/client -conn=http://kronos.mhl.tuc.gr:30002/ -c 100 -s 0 -t 0 &"
      sleep 2

      msg "Waiting for the Web server to be responsive again" 
      read -p "Press enter to continue"
     
      msg "Removing canary link deployment" 
      kubectl exec -it "$API" -n security -- ./client -arg "{\"action\":\"delete\", \"target\": \"canary-link\", \"arguments\": []}"
      
      msg "Removing detector link deployment" 
      kubectl exec -it "$API" -n security -- ./client -arg "{\"action\":\"delete\", \"target\": \"detector-link\", \"arguments\": []}"

      msg "Cleaning cluster"
      kubectl exec -n security "$AGENT_POD_1" -- bash -c "ovs-ofctl del-flows br-int cookie=0x0/-1 | true" &> /dev/null || true
      kubectl exec -n security "$AGENT_POD_2" -- bash -c "ovs-ofctl del-flows br-int cookie=0x0/-1 | true" &> /dev/null || true
      
      kubectl exec -n security "$AGENT_POD_1" -- bash -c "ovs-vsctl clear bridge br-int mirrors"
      kubectl exec -n security "$AGENT_POD_2" -- bash -c "ovs-vsctl clear bridge br-int mirrors"
      
      echo -e "\n"
      ;;
    Exit)
      echo -e "\n\n"
      msg "Cleaning cluster"

      msg "Removing applied rules from nodes"
      kubectl exec -n security "$AGENT_POD_1" -- bash -c "ovs-ofctl del-flows br-int cookie=0x0/-1 | true" &> /dev/null || true
      kubectl exec -n security "$AGENT_POD_2" -- bash -c "ovs-ofctl del-flows br-int cookie=0x0/-1 | true" &> /dev/null || true

      
      msg "Removing deployed pods"
      kubectl delete -f yamls/security
      kubectl delete -f yamls/pods

      msg "Removing qos and queue"
      kubectl exec -n kube-system "$ANTREA_POD_1" -- bash -c "ovs-vsctl --all destroy qos" &> /dev/null || true
      kubectl exec -n kube-system "$ANTREA_POD_2" -- bash -c "ovs-vsctl --all destroy qos" &> /dev/null || true
      
      kubectl exec -n kube-system "$ANTREA_POD_1" -- bash -c "ovs-vsctl --all destroy queue" &> /dev/null || true
      kubectl exec -n kube-system "$ANTREA_POD_2" -- bash -c "ovs-vsctl --all destroy queue" &> /dev/null || true

      msg "End of demo!"
      exit
      ;;
    *)
      echo "Invalid option"
      ;;
  esac
done
