apiVersion: v1
kind: Pod
metadata:
  name: snort 
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  containers:
  - name: snort
    image: linton/docker-snort
    command:
      - sleep
      - infinity
    imagePullPolicy: Always 