apiVersion: apps/v1
kind: Deployment
metadata:
  name: alice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alice
  template:
    metadata:
      labels:
        app: alice
    spec:
      containers:
      - name: alice
        image: praqma/network-multitool
        command:
          - sleep
          - infinity
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
