apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: flow-client
  name: flow-client
spec:
  selector:
    matchLabels:
      app: flow-client
  template:
    metadata:
      labels:
        app: flow-client
    spec:
      containers:
      - name: flow-client
        image: 192.168.49.1:5000/tsi-flow-client:v1.7.0
        command:
          - sleep
          - infinity
        imagePullPolicy: Always
        ports:
          - containerPort: 12345
          - containerPort: 23456
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"