---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-{{ .Values.namespace }}-ngap-net1
spec:
  config: '{ 
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "antrea-gw0",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.ngapIPadd "/" .Values.multus.ngapNetmask | nospace | quote }},
                        "gateway": {{- cat .Values.multus.ngapGateway | nospace | quote }}
                }
        ]
      }
    }'
