---

- name: Disable system swap
  shell: "swapoff -a"

- name: Remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '(?i)^([^#][\S]+\s+(none|swap)\s+swap.*)'
    line: '# \1'
    backrefs: yes
    state: present

- name: Disable swappiness and pass bridged IPv4 traffic to iptable's chains
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: 'vm.swappiness', value: '0' }
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }

- name: Add Kubernetes Signing key
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present

- name: Add Kubernetes APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'
    update_cache: false

- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Download and add the Kubernetes GPG key
  ansible.builtin.shell:
    cmd: >
      curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key |
      gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /'
    owner: root
    group: root
    mode: '0644'

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Installing kubernetes cluster packages
  apt: 
    name:
      - kubeadm=1.28.7-1.1
      - kubectl=1.28.7-1.1
      - kubelet=1.28.7-1.1

- name: Comment out disabled_plugins line for CRI
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^(\s*disabled_plugins\s*=\s*\["cri"\])'
    line: '# \1'
    backrefs: yes

- name: Restart containerd to apply new configuration
  ansible.builtin.service:
    name: containerd
    state: restarted
    enabled: yes

- name: Start kubelet
  service:
    name: kubelet
    enabled: yes
    state: started

- name: Add KUBELET_EXTRA_ARGS
  copy:
    dest: "/etc/default/kubelet"
    content: |
      KUBELET_EXTRA_ARGS="--node-ip={{ inventory_hostname }}"

