apiVersion: v1
kind: Pod
metadata:
  name: dionaea 
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  containers:
  - name: dionaea
    image: stingar/dionaea 
    command:
      - sleep
      - infinity
    imagePullPolicy: Always 
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
