apiVersion: v1
kind: Pod
metadata:
  name: malice
spec:
  containers:
  - name: malice
    image: praqma/network-multitool
    command:
      - sleep
      - infinity
    imagePullPolicy: IfNotPresent


