apiVersion: v1
kind: Pod
metadata:
  name: netperf-server
spec:
  containers:
  - name: netperf-server
    image: paultiplady/netperf 
    command:
      - sleep
      - infinity
    imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Pod
metadata:
  name: netperf-client1
spec:
  containers:
  - name: netperf-client1
    image: paultiplady/netperf 
    command:
      - sleep
      - infinity
    imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Pod
metadata:
  name: netperf-client2
spec:
  containers:
  - name: netperf-client2
    image: paultiplady/netperf 
    command:
      - sleep
      - infinity
    imagePullPolicy: IfNotPresent

