kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: kube-system
  name: deployment-manager
rules:
- apiGroups: [""]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: kube-system
  name: deployment-manager-binding
subjects:
- kind: User
  name: system:node:k8-master 
  apiGroup: ""
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: ""