apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metrics-server
    component: metrics-server
  name: metrics-server
  namespace: security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-server
      component: metrics-server
  template:
    metadata:
      labels:
        app: metrics-server
        component: metrics-server
    spec:
      containers:
        - name: metrics-server
          image: 192.168.49.1:5000/metrics-server:common
          command:
            - ./metric_server
          imagePullPolicy: Always
          ports:
            - containerPort: 4321
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-server-service
  namespace: security
spec:
  type: ClusterIP
  selector:
    app: metrics-server
    component: metrics-server
  clusterIP: 10.104.60.10
  ports:
    - port: 4321
      targetPort: 4321
      protocol: TCP
      name: loggin-in
