apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  storageClassName: standard
  hostPath:
    path: "/home/nsslm/sharedpvupf"
  #mountOptions:
  #  - hard
  #  - nfsvers=4.1
  #nfs:
  #  path: {{ .Values.persistence.volumePath | quote }}
  #  server: 192.168.2.73
