apiVersion: v1
kind: Pod
metadata:
  name: flow-control 
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  containers:
  - name: flow-control
    image: python 
    command:
      - sleep
      - infinity
    imagePullPolicy: IfNotPresent

