apiVersion: v1
kind: Pod
metadata:
  name: nslookup
spec:
  containers:
  - name: nslookup
    image: mkrishnamurthy/nslookup 
    command:
      - sleep
      - infinity
    imagePullPolicy: IfNotPresent

