apiVersion: v1
kind: Pod
metadata:
  name: snort-multus 
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  containers:
  - name: snort-multus
    image: linton/docker-snort
    command:
      - sleep
      - infinity
    imagePullPolicy: IfNotPresent
    securityContext:
       capabilities:
         add:
           - NET_ADMIN
