all: demo1 demo2 demo3 demo4

demo1:
	tar zcf demo1.tar.gz demo1/

demo2:
	tar zcf demo2.tar.gz demo2/

demo3:
	tar zcf demo3.tar.gz demo3/

demo4:
	tar zcf demo4.tar.gz demo4/

clean:
	rm -f demo1.tar.gz
	rm -f demo2.tar.gz
	rm -f demo3.tar.gz
	rm -f demo4.tar.gz

.PHONY: all demo1 demo2 demo3 demo4 clean
