all: demo1 demo2 demo3 demo4 demo5 demo6

demo1:
	tar zcf demo1.tar.gz demo1/

demo2:
	tar zcf demo2.tar.gz demo2/

demo3:
	tar zcf demo3.tar.gz demo3/

demo4:
	tar zcf demo4.tar.gz demo4/

demo5:
	tar zcf demo5.tar.gz demo5/

demo6:	
	tar zcf demo6.tar.gz demo6/

clean:
	rm -f demo1.tar.gz
	rm -f demo2.tar.gz
	rm -f demo3.tar.gz
	rm -f demo4.tar.gz
	rm -f demo5.tar.gz
	rm -f demo6.tar.gz

.PHONY: all demo1 demo2 demo3 demo4 demo5 demo6 clean
