all: demo1 demo2 demo3 demo4 demo5 demo6 demo7 demo8

demo1:
	tar zcf demo1.tar.gz demo1/

demo2:
	tar zcf demo2.tar.gz demo2/

demo3:
	tar zcf demo3.tar.gz demo3/

demo4:
	tar zcf demo4.tar.gz demo4/

demo5:
	tar zcf demo5.tar.gz demo5/

demo6:	
	tar zcf demo6.tar.gz demo6/

demo7:	
	tar zcf demo7.tar.gz demo7/

demo8:	
	tar zcf demo8.tar.gz demo8/

clean:
	rm -f *.tar.gz

.PHONY: all demo1 demo2 demo3 demo4 demo5 demo6 demo7 demo8 clean
