apiVersion: v1
kind: Pod
metadata:
  name: alice 
spec:
  containers:
  - name: alice
    image: mkrishnamurthy/nslookup 
    command:
      - sleep
      - infinity
    imagePullPolicy: IfNotPresent

