---
apiVersion: v1
kind: Pod
metadata:
  name: alice
spec:
  containers:
    - name: alice
      image: 192.168.49.1:5000/antrea-tsi:v1.0.0
      command:
        - sleep
        - infinity
      imagePullPolicy: IfNotPresent
