apiVersion: v1
kind: Pod
metadata:
  name: alice
spec:
  containers:
    - name: alice
      image: praqma/network-multitool
      command:
        - sleep
        - infinity
      imagePullPolicy: IfNotPresent
