---
apiVersion: v1
kind: Pod
metadata:
  name: alice
spec:
  containers:
    - name: alice
      image: 10.8.8.2:5000/antrea-tsi:v1.0.0
      command:
        - sleep
        - infinity
      imagePullPolicy: IfNotPresent
