---
apiVersion: v1
kind: Pod
metadata:
  name: alice
spec:
  containers:
    - name: alice
      image: localhost:5000/antrea-tsi:v1.0.1
      command:
        - sleep
        - infinity
      imagePullPolicy: IfNotPresent
