---
apiVersion: v1
kind: Pod
metadata:
  name: alice
spec:
  containers:
    - name: alice
      image: 192.168.49.1:5000/tsi-tools:1.0.22
      command:
        - sleep
        - infinity
      imagePullPolicy: IfNotPresent
