---
apiVersion: v1
kind: Pod
metadata:
  name: alice
spec:
  containers:
    - name: alice
      image: 130.207.224.36:5000/tsi-tools:1.0.22
      command:
        - sleep
        - infinity
      imagePullPolicy: IfNotPresent
