apiVersion: v1
kind: Pod
metadata:
  name: flow-control 
spec:
  containers:
  - name: flow-control
    image: 192.168.49.1:5000/tsi-flow-control:v1.0.0
    command:
      - sleep
      - infinity
    imagePullPolicy: Always 

